----------------------------------------------------------------------
-- 06_file_io_and_os.lua — Files and the OS: read, write, environment
----------------------------------------------------------------------
-- WHAT YOU'LL LEARN
--   • io.open and its mode strings ("r", "w", "a", "+", "b")
--   • The assert(io.open(...)) idiom for honest error handling
--   • read("*a"), read("*l"), read("*n") and f:lines()
--   • Writing a file, then re-reading it — into a build/ subdirectory
--     (this is EXACTLY what the Hyprland capstone in module 08 does)
--   • os.getenv, os.date, os.time, os.clock
-- HOW TO RUN
--   luajit 06_file_io_and_os.lua      (from this directory)
--   or inside nvim:  :luafile %       (with this file open)
-- PREREQUISITES: 01_error_handling.lua, 02_string_patterns.lua
----------------------------------------------------------------------

------------------------------------------------------------ 1. Where are we? (arg[0] trick)
-- File paths in this lesson are relative to THIS FILE, not to wherever
-- you happened to run luajit from. arg[0] holds the script path the
-- interpreter was started with; one pattern (lesson 02!) peels off the
-- directory part. ("." when you ran it from this directory.)

local here = arg and arg[0] and arg[0]:match("^(.*)/") or "."
print("1a lesson dir:", here)

local build_dir = here .. "/build"
-- Lua's io library can't create directories (files only). Shell out:
-- os.execute runs a command like `system()` in C — same as typing it
-- in zsh. Fine for a tutorial; real plugins use vim.uv.fs_mkdir or
-- vim.fn.mkdir instead of spawning a shell.
os.execute("mkdir -p '" .. build_dir .. "'")

------------------------------------------------------------ 2. io.open and its modes
-- io.open(path, mode) → a FILE HANDLE, or nil + error message.
-- Modes:  "r" read (default, must exist)   "w" write (TRUNCATES/creates)
--         "a" append (creates)             "r+" read+write, must exist
--         "w+" read+write, truncates       "a+" read+append
-- Add "b" for binary ("rb", "wb") — no-op on Linux, matters on Windows.
-- Handles are objects: use METHOD calls, f:read(...), f:write(...),
-- f:close() — the colon passes f itself (module 04).

-- Because io.open reports failure as nil+message (it does NOT raise),
-- the honest idiom wraps it in assert (lesson 01: assert passes its
-- arguments through on success, raises the message on nil):
--     local f = assert(io.open(path, "r"))
-- Skip the assert and a later f:read() dies with the far less helpful
-- "attempt to index a nil value (local 'f')" — you've seen that one.

local ok, err = io.open(build_dir .. "/does_not_exist.txt", "r")
print("2a open miss:", ok, "|", err)   -- nil | ...No such file or directory

local ok2, err2 = pcall(function()
  local f = assert(io.open(build_dir .. "/does_not_exist.txt", "r"))
end)
print("2b asserted:", ok2, "|", err2)  -- false | same message, now an ERROR

------------------------------------------------------------ 3. Write a file
-- "w" truncates: opening for write gives you an empty file every time.
-- f:write takes strings/numbers; it does NOT add newlines — you do.

local greeting_path = build_dir .. "/greeting.conf"
local f = assert(io.open(greeting_path, "w"))
f:write("# generated by 06_file_io_and_os.lua\n")
f:write("# on ", os.date("%Y-%m-%d %H:%M:%S"), "\n")
f:write("gaps_in = ", 3, "\n")           -- numbers are fine, coerced
f:write("gaps_out = 3\nborder_size = 1\n")
f:close()                                 -- flushes and releases the handle
print("3a wrote:", greeting_path)
-- ALWAYS close write handles. Buffered bytes may not hit disk until
-- close/flush — the classic "my generated config is empty" bug.

------------------------------------------------------------ 4. Read it back, three ways
-- read("*a") — the whole rest of the file as one string
-- read("*l") — one line, newline stripped (nil at end of file)
-- read("*n") — parse a number off the stream
-- Lua version note: 5.3+ blogs write read("a") without the star.
-- LuaJIT accepts BOTH (verified here) — but "*a" works everywhere.

local g = assert(io.open(greeting_path, "r"))
local whole = g:read("*a")
g:close()
print("4a whole file is " .. #whole .. " bytes:")
io.write(whole)          -- io.write = print without the trailing newline

local g2 = assert(io.open(greeting_path, "r"))
print("4b first line:", g2:read("*l"))
print("4c second line:", g2:read("*l"))
g2:close()

-- f:lines() → an ITERATOR over lines (lesson 03 machinery!). The handle
-- closes itself when the loop reaches end-of-file... but NOT if you
-- break out early — prefer closing explicitly like this:
local g3 = assert(io.open(greeting_path, "r"))
local count = 0
for line in g3:lines() do
  count = count + 1
  if not line:match("^#") then
    print("4d data line:", line)
  end
end
g3:close()
print("4e total lines:", count)
-- Shortcut: io.lines(path) opens AND iterates in one call.

------------------------------------------------------------ 5. The capstone pattern
-- Module 08 generates your hyprland.conf with exactly this recipe:
-- build lines in a table, concat once, write once. Rehearse it now:

local function generate_config(settings)
  local out = {}
  out[#out + 1] = "# generated " .. os.date("%Y-%m-%d")
  out[#out + 1] = "general {"
  for _, kv in ipairs(settings) do
    out[#out + 1] = ("    %s = %s"):format(kv[1], kv[2])
  end
  out[#out + 1] = "}"
  return table.concat(out, "\n") .. "\n"
  -- Why a table + concat instead of str = str .. line in a loop?
  -- Strings are immutable: each .. copies everything so far — O(n²).
  -- table.concat builds the result once. Same reason as in module 03.
end

local conf_text = generate_config({
  { "gaps_in", 3 }, { "gaps_out", 3 }, { "border_size", 1 },
})
local conf_path = build_dir .. "/mini_hyprland.conf"
local out = assert(io.open(conf_path, "w"))
out:write(conf_text)
out:close()

-- Round-trip check — re-read and verify, so we KNOW it landed:
local back = assert(io.open(conf_path, "r"))
local reread = back:read("*a")
back:close()
print("5a round-trip intact:", reread == conf_text)
print("5b generated file:")
io.write(reread)

------------------------------------------------------------ 6. The os library
-- os.getenv(name) → environment variable or nil. Your zsh exports show
-- up here — this is how a Lua Hyprland generator can read $HOME.
print("6a HOME:", os.getenv("HOME"))
print("6b missing var:", os.getenv("DEFINITELY_NOT_SET_XYZ"))   -- nil, no error

-- os.date(format[, time]) formats a timestamp (strftime codes, like
-- `date +%Y` in the shell). The special "*t" gives a TABLE instead:
print("6c date:", os.date("%Y-%m-%d %H:%M:%S"))
local now = os.date("*t")
print("6d table:", now.year, now.month, now.day, "wday=" .. now.wday)

-- os.time() → seconds since the epoch. os.time(table) goes the other
-- way — great for date arithmetic:
local t_now = os.time()
local newyear = os.time({ year = now.year + 1, month = 1, day = 1 })
print("6e epoch now:", t_now)
print("6f days to new year:", math.floor(os.difftime(newyear, t_now) / 86400))

-- os.clock() → CPU seconds used; you met it timing loops in lesson 05.
-- Also good to know: os.remove(path), os.rename(old, new) — both return
-- nil + message on failure, so they take the assert idiom too.

------------------------------------------------------------ TRY IT
-- 1. Change "w" to "a" in section 3 and run the file twice. Read
--    build/greeting.conf. Now explain why generators (section 5) want
--    "w", never "a".
-- 2. Use f:read("*n") to pull the 3 out of "gaps_in = 3" — you'll need
--    to read past "gaps_in = " first (read the *l of the comment lines,
--    then... experiment; *n is picky and that's the lesson).
-- 3. Write parse_config(path) that returns a table from key = value
--    lines using io.lines + your lesson-02 pattern. Point it at
--    build/mini_hyprland.conf (mind the indentation and the { } lines).
-- 4. Print a timestamped log line like [2026-07-09 14:03:12] using
--    os.date, then append (mode "a"!) it to build/run.log — run the
--    file three times and check the log grows.
